version: '3.0'
services:
  backend:
    image: "$BACKEND_IMAGE"
    container_name: laravel670_backend
    env_file: ./.env
    build:
      context: './'
      dockerfile: 'docker/php/Dockerfile'
      args:
        COMPOSER_AUTH: '{"github-oauth": {"github.com": "${COMPOSER_GITHUB_TOKEN}"}}'
  frontend:
    image: "$FRONTEND_IMAGE"
    container_name: laravel670_frontend
    build:
      context: './'
      dockerfile: 'docker/nginx/Dockerfile'
    depends_on:
      - backend
