version: '3'
services:
    nginx:
        image: cloudigital/nginx
        ports:
            - "6789:8001"
        networks:
            - cloudigital_network
        links:
            - web_Laravel_v670
        deploy:
            placement:
                constraints: [node.role == manager]
    web_Laravel_v670:
        image: cloudigital/Laravel_v670
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
        networks:
            - cloudigital_network
        deploy:
            mode: replicated
            replicas: 4
            placement:
                constraints: [node.role == worker]
            resources:
                limits:
                    cpus: '0.1'
                    memory: 256M
    database:
        image: gmgdocker/mysql5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=mysql_container_root"
            - "MYSQL_USER=cloudigital"
            - "MYSQL_PASSWORD=cloudigital@mysql"
            - "MYSQL_DATABASE=Laravel_v670"
        ports:
            - "33061:3306"
        networks:
            - cloudigital_network
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == worker]

networks:
    cloudigital_network:
